# 개발용 Docker Compose - Hot Reload 지원
version: '3.8'

services:
  # 백엔드 개발 서버
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: claude-todo-backend-dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./data/dev.db
    volumes:
      - backend-data-dev:/app/data
      - ./backend/src:/app/src:ro  # 소스 코드 실시간 반영
      - ./backend/prisma:/app/prisma:ro
    networks:
      - claude-todo-dev-network
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 프론트엔드 개발 서버
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: claude-todo-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
    depends_on:
      backend-dev:
        condition: service_healthy
    networks:
      - claude-todo-dev-network
    command: npm run dev

volumes:
  backend-data-dev:
    driver: local

networks:
  claude-todo-dev-network:
    driver: bridge